apiVersion: v1
kind: Service
metadata:
  labels:
    app: fakedev-exporter
  name: fakedev-exporter
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 9999
    targetPort: http
  selector:
    app: fakedev-exporter
