{
 "title": "GPU metrics",
 "description": "Selectable output from multiple GPU exporters in the cluster",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "exporter",
    "label": "GPU metric exporter",
    "query": "Collectd : collectd_gpu_sysman, XPU Manager : xpum"
   },
   { "name": "sort", "label": "Sorting", "query": "Top : top, Bottom : bottom" },
   { "name": "gpus", "label": "Max nodes", "query": "3,5,8,12,16,20" },
   { "name": "node", "label": "GPU node", "query": { "query": "${exporter}_frequency_mhz" } },
   { "name": "engines", "label": "Max engines", "query": "5,8,12,16,20" }
  ]
 },
 "panels": [
  {
   "title": "Power usage for $sort-$gpus GPUs in all nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "${sort}k($gpus, sum by (node,pci_bdf,pci_dev)(${exporter}_power_watts))",
     "legendFormat": "{{node}} [{{pci_bdf}}] ({{pci_dev}})"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "${sort}k($gpus, sum by (node,pci_bdf)(avg_over_time(${exporter}_power_watts[$__range])))",
     "legendFormat": "{{node}} [{{pci_bdf}}]"
    }
   ]
  },
  {
   "title": "GPU power / energy usage ($node)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "${exporter}_power_watts{node=\"$node\"}",
     "legendFormat": "{{dev_file}} [{{pci_bdf}}/{{sub_dev}}] watts"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "targets": [
    {
     "expr": "${exporter}_energy_joules_total{node=\"$node\"}",
     "legendFormat": "{{dev_file}} [{{pci_bdf}}/{{sub_dev}}] total"
    }
   ]
  },
  {
   "title": "GPU temperature / RAS error counts ($node)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "${exporter}_temperature_celsius{node=\"$node\"}",
     "legendFormat": "{{dev_file}} [{{pci_bdf}}/{{sub_dev}}] {{location}}"
    }
   ]
  },
  {
   "title": "Error counters",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "${exporter}_all_errors_total{node=\"$node\"}",
     "legendFormat": "{{dev_file}}[{{sub_dev}}] total/{{type}}"
    },
    {
     "expr": "${exporter}_resets_total{node=\"$node\"}",
     "legendFormat": "{{dev_file}}[{{sub_dev}}] resets"
    },
    {
     "expr": "${exporter}_programming_errors_total{node=\"$node\"}",
     "legendFormat": "{{dev_file}}[{{sub_dev}}] HW programming"
    },
    {
     "expr": "${exporter}_driver_errors_total{node=\"$node\"}",
     "legendFormat": "{{dev_file}}[{{sub_dev}}] driver communication"
    },
    {
     "expr": "sum by (dev_file,sub_dev) (${exporter}_compute_errors_total{node=\"$node\"})",
     "legendFormat": "{{dev_file}}[{{sub_dev}}] compute"
    },
    {
     "expr": "sum by (dev_file,sub_dev) (${exporter}_fixed_function_errors_total{node=\"$node\"})",
     "legendFormat": "{{dev_file}}[{{sub_dev}}] fixed-function"
    },
    {
     "expr": "sum by (dev_file,sub_dev) (${exporter}_cache_errors_total{node=\"$node\"})",
     "legendFormat": "{{dev_file}}[{{sub_dev}}] cache ECC"
    },
    {
     "expr": "sum by (dev_file,sub_dev) (${exporter}_display_errors_total{node=\"$node\"})",
     "legendFormat": "{{dev_file}}[{{sub_dev}}] display ECC"
    }
   ]
  },
  {
   "title": "GPU memory usage / ratio ($node)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "${exporter}_memory_used_bytes{node=\"$node\"}",
     "legendFormat": "{{dev_file}} [{{pci_bdf}}/{{sub_dev}}] {{location}} ({{type}}-{{function}})"
    },
    {
     "expr": "${exporter}_memory_bytes{node=\"$node\"}",
     "legendFormat": "{{dev_file}} [{{pci_bdf}}/{{sub_dev}}] {{location}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "${exporter}_memory_usage_ratio{node=\"$node\"}",
     "legendFormat": "{{dev_file}} [{{pci_bdf}}/{{sub_dev}}] {{location}} ({{type}}-{{function}})"
    },
    {
     "expr": "${exporter}_memory_ratio{node=\"$node\"}",
     "legendFormat": "{{dev_file}} [{{pci_bdf}}/{{sub_dev}}] {{location}}"
    }
   ]
  },
  {
   "title": "GPU memory BW utilization / fabric port throughput ($node)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "${exporter}_memory_bw_ratio{node=\"$node\"}",
     "legendFormat": "{{dev_file}} [{{pci_bdf}}/{{sub_dev}}] {{location}} {{direction}} ({{type}})"
    },
    {
     "expr": "${exporter}_memory_ratio{node=\"$node\"}",
     "legendFormat": "{{dev_file}} [{{pci_bdf}}/{{sub_dev}}] {{src}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "${exporter}_fabric_port_bytes{node=\"$node\"}",
     "legendFormat": "{{dev_file}} [{{pci_bdf}}/{{sub_dev}}]  {{direction}} ({{port}}-{{remote}})"
    }
   ]
  },
  {
   "title": "GPU frequency / throttling ($node)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "Mhz" } },
   "targets": [
    {
     "expr": "${exporter}_frequency_mhz{node=\"$node\"}",
     "legendFormat": "{{dev_file}} [{{pci_bdf}}/{{sub_dev}}] {{location}} ({{type}}-{{function}})"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "${exporter}_throttled_ratio{node=\"$node\"}",
     "legendFormat": "{{dev_file}} [{{pci_bdf}}/{{sub_dev}}] {{location}} ({{type}})"
    }
   ]
  },
  {
   "title": "$sort-$engines GPU engine + engine group utilization ($node)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 }
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "${sort}k($engines, ${exporter}_engine_ratio{node=\"$node\"})",
     "legendFormat": "{{dev_file}}[{{sub_dev}}] {{type}}"
    },
    {
     "expr": "${sort}k($engines, ${exporter}_engine_group_ratio{node=\"$node\"})",
     "legendFormat": "{{dev_file}}[{{sub_dev}}] {{type}}"
    }
   ]
  },
  {
   "title": "Counter versions of the above gauges",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 }
  },
  {
   "title": "Engine use time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "${exporter}_engine_use_secs_total{node=\"$node\", type!~\".*-[0-9]+\"}",
     "legendFormat": "{{dev_file}} [{{pci_bdf}}/{{sub_dev}}] {{type}}"
    }
   ]
  },
  {
   "title": "Memory BW usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(${exporter}_memory_bw_bytes_total{node=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{dev_file}} [{{pci_bdf}}/{{sub_dev}}] rate/{{direction}}"
    },
    {
     "expr": "rate(${exporter}_memory_write_bytes_total{node=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{dev_file}} [{{pci_bdf}}/{{sub_dev}}] rate/write"
    },
    {
     "expr": "rate(${exporter}_memory_read_bytes_total{node=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{dev_file}} [{{pci_bdf}}/{{sub_dev}}] rate/read"
    }
   ]
  },
  {
   "title": "Frequency throttle time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "${exporter}_throttled_secs_total{node=\"$node\"}",
     "legendFormat": "{{dev_file}} [{{pci_bdf}}/{{sub_dev}}] {{location}} ({{type}}) total"
    }
   ]
  }
 ]
}